# Creating arrays

In [63]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
 np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
>>> np.ones((2,3),dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [14]:
 np.arange(10,100,20)

array([10, 30, 50, 70, 90])

In [15]:
 np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
 np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
 np.linspace(0,1,6) 

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [34]:
 np.linspace(0,20,100) 

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [36]:
 np.full((2,2),70)

array([[70, 70],
       [70, 70]])

In [38]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
 myrandom = np.random.random((2,2)) 

In [73]:
myrandom

array([[0.04848251, 0.67640216],
       [0.72134591, 0.82497057]])

# Saving and loading

In [60]:
np.save('myrandom',myrandom)

In [61]:
np.load('myrandom.npy')

array([[0.04848251, 0.67640216],
       [0.72134591, 0.82497057]])

# Inspecting

In [65]:
myrandom.shape

(2, 2)

In [66]:
myrandom.size

4

In [67]:
len(myrandom)

2

In [68]:
myrandom.ndim

2

In [70]:
myrandom.dtype

dtype('float64')

In [71]:
myrandom.dtype.name

'float64'

In [72]:
myrandom.astype(int)

array([[0, 0],
       [0, 0]])

In [74]:
 np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Arithmetic

In [82]:
a = np.array([(1, 2, 3, 4),(10, 20, 30, 40)])

In [84]:
b = a * 2

In [85]:
b

array([[ 2,  4,  6,  8],
       [20, 40, 60, 80]])

In [86]:
a - b

array([[ -1,  -2,  -3,  -4],
       [-10, -20, -30, -40]])

In [87]:
b / a

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [88]:
a * b

array([[   2,    8,   18,   32],
       [ 200,  800, 1800, 3200]])

# Comparison

In [89]:
a == b

array([[False, False, False, False],
       [False, False, False, False]])

In [90]:
a > 1

array([[False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [91]:
a

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

# Aggregate Functions

In [93]:
a.sum()

110

In [94]:
a.min()

1

In [95]:
a.max()

40

In [99]:
a.mean()

13.75

In [102]:
np.std(a)

13.77270852083932

# Sorting

In [108]:
x = np.random.random(3)

In [109]:
x

array([0.86196341, 0.25833532, 0.89824223])

In [110]:
x.sort()

In [111]:
x

array([0.25833532, 0.86196341, 0.89824223])

In [113]:
y = np.random.random([3,5])

In [114]:
y

array([[0.61227965, 0.9281185 , 0.02922881, 0.30892819, 0.23968307],
       [0.71464571, 0.49140577, 0.39429648, 0.29022578, 0.57608464],
       [0.1453522 , 0.40703633, 0.51152819, 0.3187904 , 0.63196744]])

In [115]:
y.sort()

In [116]:
y

array([[0.02922881, 0.23968307, 0.30892819, 0.61227965, 0.9281185 ],
       [0.29022578, 0.39429648, 0.49140577, 0.57608464, 0.71464571],
       [0.1453522 , 0.3187904 , 0.40703633, 0.51152819, 0.63196744]])

# Slicing and subsetting