In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
 np.zeros((3,4)) 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
>>> np.ones((2,3),dtype=np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [14]:
 np.arange(10,100,20)

array([10, 30, 50, 70, 90])

In [15]:
 np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [16]:
 np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [25]:
 np.linspace(0,1,6) 

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [34]:
 np.linspace(0,20,100) 

array([ 0.        ,  0.2020202 ,  0.4040404 ,  0.60606061,  0.80808081,
        1.01010101,  1.21212121,  1.41414141,  1.61616162,  1.81818182,
        2.02020202,  2.22222222,  2.42424242,  2.62626263,  2.82828283,
        3.03030303,  3.23232323,  3.43434343,  3.63636364,  3.83838384,
        4.04040404,  4.24242424,  4.44444444,  4.64646465,  4.84848485,
        5.05050505,  5.25252525,  5.45454545,  5.65656566,  5.85858586,
        6.06060606,  6.26262626,  6.46464646,  6.66666667,  6.86868687,
        7.07070707,  7.27272727,  7.47474747,  7.67676768,  7.87878788,
        8.08080808,  8.28282828,  8.48484848,  8.68686869,  8.88888889,
        9.09090909,  9.29292929,  9.49494949,  9.6969697 ,  9.8989899 ,
       10.1010101 , 10.3030303 , 10.50505051, 10.70707071, 10.90909091,
       11.11111111, 11.31313131, 11.51515152, 11.71717172, 11.91919192,
       12.12121212, 12.32323232, 12.52525253, 12.72727273, 12.92929293,
       13.13131313, 13.33333333, 13.53535354, 13.73737374, 13.93

In [36]:
 np.full((2,2),70)

array([[70, 70],
       [70, 70]])

In [38]:
# identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])